In [4]:
import joblib
import pandas as pd

In [5]:
model = joblib.load("models/fraud_model.pkl")
scaler = joblib.load("models/scaler.pkl")

print("Model loaded successfully.")
print("Scaler loaded successfully.")

Model loaded successfully.
Scaler loaded successfully.

In [6]:
df = pd.read_csv("creditcard.csv")

df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [7]:
sample = df.drop("Class", axis=1).iloc[[100]]
actual = df["Class"].iloc[100]

print(sample)

     Time        V1        V2        V3        V4        V5        V6  \
100  68.0  1.156939  0.037215  0.556799  0.519507 -0.479754 -0.352714

           V7        V8        V9  ...       V20       V21       V22  \
100 -0.222487  0.158242  0.011252  ... -0.221852 -0.182662 -0.612268

          V23       V24       V25      V26       V27       V28  Amount
100  0.197305  0.174883  0.032497  0.09948 -0.026816  0.004199    2.69

[1 rows x 30 columns]

In [8]:
sample_scaled = scaler.transform(sample)

In [9]:
prediction = model.predict(sample_scaled)

print("Prediction:", prediction[0])
print("Actual:", actual)

Prediction: 0
Actual: 0

c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [10]:
probability = model.predict_proba(sample_scaled)

print(probability)

[[0.96121276 0.03878724]]

c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [11]:
if prediction[0] == 1:
    print("🚨 Fraud Transaction")
else:
    print("✅ Normal Transaction")

print("--------------------------------")

print("Probability")

print("Normal :", probability[0][0])

print("Fraud  :", probability[0][1])

print("--------------------------------")

print("Actual :", actual)

✅ Normal Transaction
--------------------------------
Probability
Normal : 0.9612127556438792
Fraud  : 0.03878724435612084
--------------------------------
Actual : 0

In [12]:
samples = df.drop("Class", axis=1).iloc[0:10]

actual = df["Class"].iloc[0:10]

samples_scaled = scaler.transform(samples)

prediction = model.predict(samples_scaled)

result = pd.DataFrame({

    "Actual": actual.values,

    "Prediction": prediction

})

result

c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

   Actual  Prediction
0       0           0
1       0           0
2       0           1
3       0           0
4       0           0
5       0           0
6       0           0
7       0           0
8       0           0
9       0           0

In [13]:
X = df.drop("Class", axis=1)

y = df["Class"]

X_scaled = scaler.transform(X)

prediction = model.predict(X_scaled)

result = pd.DataFrame({

    "Actual": y,

    "Prediction": prediction

})

result.head(20)

c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

    Actual  Prediction
0        0           0
1        0           0
2        0           1
3        0           0
4        0           0
5        0           0
6        0           0
7        0           0
8        0           0
9        0           0
10       0           0
11       0           0
12       0           0
13       0           0
14       0           1
15       0           0
16       0           0
17       0           0
18       0           1
19       0           0